# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colMediansArma <- function(x, ignore_missing) {
    .Call(`_MALDIquant_colMediansArma`, x, ignore_missing)
}

colMeansArma <- function(x, ignore_missing) {
    .Call(`_MALDIquant_colMeansArma`, x, ignore_missing)
}

